### ISSUE TITLE
Crash with "にゃーん"

### ISSUE THREAD

**Issue by pocke** [pocke/ripper-api#1]
```
$ curl http://localhost:5000 -d 'にゃーん' -X POST
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   912  100   900  100    12   101k   1392 --:--:-- --:--:-- --:--:--  109k
Puma caught this error: "\xE3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
/home/pocke/.gem/ruby/2.4.0/gems/json-2.0.3/lib/json/common.rb:224:in `encode'
/home/pocke/.gem/ruby/2.4.0/gems/json-2.0.3/lib/json/common.rb:224:in `generate'
/home/pocke/.gem/ruby/2.4.0/gems/json-2.0.3/lib/json/common.rb:224:in `generate'
/home/pocke/.gem/ruby/2.4.0/gems/json-2.0.3/lib/json/common.rb:394:in `dump'
app.ru:21:in `response_body'
app.ru:9:in `call'
/home/pocke/.gem/ruby/2.4.0/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
/home/pocke/.gem/ruby/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
/home/pocke/.gem/ruby/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
/home/pocke/.gem/ruby/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
/home/pocke/.gem/ruby/2.4.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by pocke** [comment]
It's fixed by 90ccd358ba07bf6c2720e0fa6467a49ae06960e7
